databaseChangeLog:
  - changeSet:
      id: 1761662801002-1
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createSequence:
            incrementBy: 50
            sequenceName: d_loadosf_entity_seq
            startValue: 1
  - changeSet:
      id: 1761662801002-2
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_d_loadosf_entity
                  name: id
                  type: BIGINT
              - column:
                  name: msgheader_id
                  type: BIGINT
              - column:
                  name: lcuz_id
                  type: BIGINT
              - column:
                  name: lcdop_id
                  type: BIGINT
              - column:
                  name: basta_entity_id
                  type: BIGINT
              - column:
                  name: maika_id
                  type: BIGINT
              - column:
                  name: sapruga_id
                  type: BIGINT
              - column:
                  name: molba_id
                  type: BIGINT
              - column:
                  name: domakin_id
                  type: BIGINT
              - column:
                  name: euroda_id
                  type: BIGINT
              - column:
                  name: voit_id
                  type: BIGINT
              - column:
                  name: images_id
                  type: BIGINT
              - column:
                  name: fingers_id
                  type: BIGINT
              - column:
                  name: version
                  type: FLOAT
            tableName: d_loadosf_entity
  - changeSet:
      id: 1761662801002-3
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: basta_entity_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_BASTA_ENTITY
            referencedColumnNames: id
            referencedTableName: d_basta_row
  - changeSet:
      id: 1761662801002-4
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: domakin_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_DOMAKIN
            referencedColumnNames: id
            referencedTableName: d_domakin_row
  - changeSet:
      id: 1761662801002-5
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: euroda_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_EURODA
            referencedColumnNames: id
            referencedTableName: d_euroda_row
  - changeSet:
      id: 1761662801002-6
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: fingers_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_FINGERS
            referencedColumnNames: id
            referencedTableName: d_fingers_row
  - changeSet:
      id: 1761662801002-7
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: images_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_IMAGES
            referencedColumnNames: id
            referencedTableName: d_images_row
  - changeSet:
      id: 1761662801002-8
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: lcdop_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_LCDOP
            referencedColumnNames: id
            referencedTableName: d_lcdop_row
  - changeSet:
      id: 1761662801002-9
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: lcuz_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_LCUZ
            referencedColumnNames: id
            referencedTableName: d_lcuz_row
  - changeSet:
      id: 1761662801002-10
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: maika_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_MAIKA
            referencedColumnNames: id
            referencedTableName: d_maika_row
  - changeSet:
      id: 1761662801002-11
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: molba_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_MOLBA
            referencedColumnNames: id
            referencedTableName: molba_row
  - changeSet:
      id: 1761662801002-12
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: msgheader_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_MSGHEADER
            referencedColumnNames: id
            referencedTableName: d_msgheader_row
  - changeSet:
      id: 1761662801002-13
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: sapruga_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_SAPRUGA
            referencedColumnNames: id
            referencedTableName: d_sapruga_row
  - changeSet:
      id: 1761662801002-14
      author: oleg
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: voit_id
            baseTableName: d_loadosf_entity
            constraintName: FK_D_LOADOSF_ENTITY_ON_VOIT
            referencedColumnNames: id
            referencedTableName: d_voit_row

